name: Deploy to Timeweb Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          echo "🚀 Начинаем деплой..."
          cd /var/www/support-bday
          echo "📁 Текущая директория: $(pwd)"
          echo "📥 Получаем последние изменения..."
          git pull origin main
          echo "📦 Останавливаем контейнеры..."
          docker-compose down
          echo "🔨 Пересобираем образы..."
          docker-compose build --no-cache
          echo "🚀 Запускаем новые контейнеры..."
          docker-compose up -d
          echo "🧹 Очищаем неиспользуемые образы..."
          docker system prune -f
          echo "✅ Деплой завершен успешно!"
          echo "📊 Статус контейнеров:"
          docker-compose ps 