name: Webhook Deploy

on:
  push:
    branches: [ main ]

jobs:
  webhook-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger webhook
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "X-GitHub-Event: push" \
          -d '{"ref":"refs/heads/main"}' \
          http://${{ secrets.HOST }}:3001/webhook 